# Generated by Django 5.0.6 on 2024-06-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plp_ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Availaility',
            field=models.BooleanField(default=True),
        ),
    ]
